name: plantesmedicinales
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.14.0
  firebase_ui_auth: ^1.10.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.6.0
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  line_awesome_flutter: ^2.0.0
  animated_bottom_navigation_bar: ^0.3.3
  page_transition: ^2.0.5
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.1

  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/plantss.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/plantss.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
